#!/bin/sh

set -e

REPO="$(realpath "$(dirname "$(realpath "$0")")/..")"

if [ -f "$REPO/Makefile" ]; then make -C "$REPO" distclean; fi

export LDFLAGS="-L$REPO/vendor/libkernaux"
export CFLAGS="-I$REPO/vendor/libkernaux/include"

"$REPO/configure"
